---
title: "gtrends in list columns"
author: "Ian Handel"
date: "29/01/2019"
output: github_document
---

```{r}
library(tidyverse)
library(gtrendsR)
library(fs) # for path_sanitise
library(lubridate) # for now()
```


### Build search table

try adding multi-term searches


```{r}
# The signs to search for
signs <- c(
  "",
  "ill",
  "diarrhoea",
  "base-jumping-on-acid"
)

# The dog types to search for
dogs <- c(
  "puppy",
  "dog"
)

# All combinations of above (remove leading/trailing spaces)

searches <- tibble(dogs) %>%
  crossing(signs) %>%
  mutate(
    search = str_glue("{dogs} {signs}"),
    search = str_squish(search)
  ) %>% 
  group_by(dogs) %>%
  summarise(search = list(search)) %>% 
  ungroup()

head(searches)
```


### For each search do a gtrends call

```{r}
searches <- searches %>%
  mutate(gtrend = map(search, gtrends,
    geo = "GB",
    time = "2011-01-01 2018-01-01"
  ))

head(searches)
```

### Extract some dataframes into their own columns

```{r}
searches <- searches %>%
  mutate(
    iot = map(gtrend, "interest_over_time"),
    ibr = map(gtrend, "interest_by_region"),
    rt = map(gtrend, "related_topics")
  )

head(searches)
```

### make a safe filename and save

```{r, eval = FALSE}
rds_path <- str_glue("gtrend_searches_{now()}.rds") %>%
  path_sanitize() %>%
  str_replace(" ", "_")

write_rds(searches, rds_path)
```


### Unnest, say iot, then try a plot

uses [this solution](https://stackoverflow.com/questions/47224831/using-tidyr-unnest-with-null-values) to deal with NULL dataframes

uses ```right_join(searches %>% select_if(~!is_list(.)))``` to include null search info


```{r}
iot <- searches %>%
  filter(!map_lgl(iot, is.null)) %>% 
  unnest(iot) %>% 
  right_join(searches %>% select_if(~!is_list(.))) %>% 
  mutate(hits = case_when(hits == "<1" ~ 0L,
                          hits == 0    ~ NA_integer_,
                          TRUE         ~ parse_integer(hits)))

ggplot(iot) +
  aes(date, hits, colour = keyword) +
  geom_line() +
  facet_wrap(~ str_wrap(keyword,width = 20)) +
  theme(legend.position = "none")
```
